default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: your_postgresql_password

development:
  <<: *default
  database: blogs_development

test:
  <<: *default
  database: blogs_test

production:
  <<: *default
  database: blogs_production
  username: blogs
  password: <%= ENV['BLOGS_DATABASE_PASSWORD'] %>

# local   replication     all                                     peer
# host    replication     all             127.0.0.1/32            md5
# host    replication     all             ::1/128                 md5
