name: RSpec Tests

on:
  push:
    branches:
      - main  # Run on push events to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  rspec:
    name: Run RSpec tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0  # Adjust as per your project's Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up the database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:schema:load

      - name: Run RSpec tests
        run: |
          bundle exec rspec
